### ISSUE TITLE
Update the memory requirements for Guanaco in the readme.

### ISSUE THREAD

**Issue by fire** [petals-infra/chat.petals.dev#19]
Anyone got rough numbers?

**Comment by borzunov** [comment]
Hi @fire,

They are exactly the same as for LLaMA, since the local part of the model will be identical (the only change is that you request servers to use `active_adapter = "timdettmers/guanaco-65b"`). I'll add this info to readme.

If you'd like to host both Guanaco and LLaMA, you can even share tensors between them with minor code changes.

Let me know if you have any other questions!
