### ISSUE TITLE
Is there any difference between the BLOOMZ-176B accessible through WebSocket API and the original BLOOMZ-176B?

### ISSUE THREAD

**Issue by lexzhou** [petals-infra/chat.petals.dev#24]
Hi,

Thank you for making this enormous open-source effort! It's indeed a remarkable work. 

There is one thing that puzzles me, and I couldn't find any reliable source to confirmit: any difference between the BLOOMZ-176B accessed through WebSocket API (as you described in your readme file) and the original BLOOMZ-176 released here: https://huggingface.co/bigscience/bloomz.

I'm inclined toward believing they're the same model and Petals Chatbot just uses the WebSocket API internally as well, but it would be really appreciated to have someone confirming this.

**Comment by borzunov** [comment]
Hi @lexzhou,

The model is the same, except that we use quantization to int8/nf4 on servers to use less GPU memory. The int8 quantization does not significantly reduce quality, see benchmarks:

<img width="387" alt="Screenshot 2023-07-22 at 12 22 20" src="https://github.com/petals-infra/chat.petals.dev/assets/8748943/87a36343-a9da-452a-b943-298e499a0ccd">

nf4 may be worse, we can test it if you're interested. So far, we've only tested quality of nf4-quantized LLaMAs and also didn't see significant reduction of quality.

**Comment by lexzhou** [comment]
Huge thanks @borzunov, for the clarification. It's fine if it's a quantized version (the slight performance degradation is acceptable). Our team will try to contribute GPUs to get BLOOMZ running for some experiments.

Btw, would you mind telling me if the LLaMA-2 models are also in the same quantization conditions? I've used the following codes to check if the model is quantized and it says the LLaMA-2 is not quantized.

```
import torch

model_name = "meta-llama/Llama-2-70b-hf"
token="MY_TOKEN"
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=False, add_bos_token=False,
                                          use_auth_token=token)
model = AutoDistributedModelForCausalLM.from_pretrained(model_name,
                                                        use_auth_token=token)
model = model.cuda()

def check_quantization(model):
    for module in model.modules():
        if isinstance(module, torch.quantization.QuantStub) or isinstance(module, torch.nn.quantized.modules.linear.Linear):
            return True
    return False

is_quantized = check_quantization(model)
print(f"Is the model quantized? {is_quantized}")  # the result says False
```

But now I feel the code may not work for all kinds of quantization techniques, and probably the LLaMA-2 is also quantized..

**Comment by borzunov** [comment]
@lexzhou Yes, Llama 2 and Llama are also nf4-quantized. You can see the quantization mode on https://health.petals.dev - expand the **Throughput »** column and you'll see this:

<img width="724" alt="Screenshot 2023-07-22 at 20 50 16" src="https://github.com/petals-infra/chat.petals.dev/assets/8748943/16a3806e-4c83-4f30-a90d-5631f10c3656">

Right now, Llamas are nf4-quantized by default and everyone loads them this way. BLOOM is int8-quantized by default, but people in the swarm still load it in nf4 to fit more blocks per GPU.

Re your code - you won't be able to check it this way since the quantized blocks are stored on remote servers. Your local model only has "fake" `nn.Module`s that route all inference/forward/backward requests through a chain of remote servers. Also, we use https://github.com/TimDettmers/bitsandbytes instead of `torch.nn.quantized`.

**Comment by lexzhou** [comment]
Right -- that matches with the hypotheses that I had in mind. Big thanks Alexander again for the help.
