### ISSUE TITLE
How to remove the installation

### ISSUE THREAD

**Issue by DewiarQR** [petals-infra/chat.petals.dev#28]
I tried to install your solution on linux ubuntu server, the solution did not work.
After that, the server stopped responding after 15 minutes of inactivity, and the sites on it stopped working now.
How to remove your solution from the server and restore its normal operation?

**Comment by borzunov** [comment]
Hi @DewiarQR,

Just reboot your server - the web app won't start after reboot unless you made it to (I assume you did not, since it is not covered in the instruction).

Re "the server stopped responding" - one reason for it could be that your server exceeded the amount of free memory. You can avoid that by keeping only one model served in `config.py`. See more info here: https://github.com/petals-infra/chat.petals.dev#backends-system-requirements

**Comment by DewiarQR** [comment]
Thanks for your reply. In fact, the server began to shut down due to changes in settings in standby mode. This instruction helped to solve the problem: https://en-wiki.ikoula.com/en/Disable_Ubuntu_sleep_mode
The only thing is that the chat itself could not be tested. The described installation method did not allow anything to start, possibly because Nginx and Apache are already running on the server. Probably running flask and gunicorn conflicts with these servers.

**Comment by borzunov** [comment]
@DewiarQR An easy way is to host this app on a port different from 80 (the one already occupied by nginx). You can use 31330 for example.

Alternatively, you can set up gunicorn in such a way that it's available to nginx - there are plenty of guides for that across the Internet, or I can share some configs I use.

**Comment by borzunov** [comment]
@DewiarQR The default commands run the chat web app at port 5000, so it doesn't conflict with anything. You can open it at `http://your_domain:5000`.

Alternatively, you can set up gunicorn in such a way that it's served by nginx on a certain URL (e.g., `http://your_domain/chat`) - there are plenty of guides for that across the Internet, or I can share some configs I use.

**Comment by borzunov** [comment]
I'm closing this, let us know if you meet any other issues.
