### ISSUE TITLE
resume model downloads

### ISSUE THREAD

**Issue by lightningorb** [petals-infra/chat.petals.dev#49]
Hi,

I'm new to petals, with a fairly low bandwidth connection. Everytime the download fails, it seems the shard has to be re-downloaded from the start.

Can't petals have resumable downloads? What's being used? LFS? I'm seeing:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
```

Happy to look into this if you point me in the right direction.

**Comment by lightningorb** [comment]
Also i'm not sure why i'm getting these worker timeouts, or SIGKILLs:

```
Downloading shards:   0%|                                                                                                                      | 0/2 [00:00<?, ?it/s[2023-09-27 03:09:42 +0000] [34368] [CRITICAL] WORKER TIMEOUT (pid:34369)██████████████████████████▍                             | 2.71G/4.12G [16:21<08:23, 2.82MB/s]
Downloading shards:  50%|██████████████████████████████████████████████████████▌                                                      | 1/2 [16:21<16:21, 981.88s/it]
[2023-09-27 03:09:42 +0000] [34369] [INFO] Worker exiting (pid: 34369)
Downloading (…)of-00014.safetensors:  66%|████████████████████████████████████████████████████████▍                             | 2.71G/4.12G [16:21<08:34, 2.76MB/s]
[2023-09-27 03:09:43 +0000] [34368] [ERROR] Worker (pid:34369) was sent SIGKILL! Perhaps out of memory?

**Comment by borzunov** [comment]
Hi @lightningorb,

> Also i'm not sure why i'm getting these worker timeouts, or SIGKILLs

You get these because Petals doesn't manage to download all the weights in the startup timeout specified to gunicorn (`--timeout 1000`, i.e., 1000 sec). Please specify `--timeout 10000` to increase this timeout and avoid the app being killed.

Alternatively, you can run the app without gunicorn first, so it downloads all the weights without any timeouts (run `flask run --host=0.0.0.0 --port=5000`). Then you'll be able to run it with gunicorn, and the app will reuse the weights saved on disk.

> Can't petals have resumable downloads? What's being used? LFS?

Weights are downloaded by the underlying [HF Transformers](https://github.com/huggingface/transformers) code - it downloads them from HF Model Hub, where they are stored in Git LFS.

Resumable downloads are possible in principle but would require changes in HF Transformers (e.g., so we keep a registry of previous downloads that can be resumed). We are not ready to work on this, but you can create an issue in the HF Transformers repo if necessary.
